version: '3.8'
services:
    # MongoDB: https://hub.docker.com/_/mongo/
    mongo:
      image: mongo:latest
      networks:
        - graylog
      volumes:
        - mongo_data:/data/db
      restart: always
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
      volumes:
        - es_data:/usr/share/elasticsearch/data      
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m -Des.transport.cname_in_publish_address=true"
      restart: always
      #ulimits:
        #memlock:
          #soft: -1
          #hard: -1
      deploy:
        resources:
          limits:
            memory: 1g
      networks:
        - graylog
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
      image: graylog/graylog:5.1.5
      volumes:
        - graylog_data:/usr/share/graylog/data
      environment:
        - GRAYLOG_ROOT_TIMEZONE=America/Chicago
        - GRAYLOG_ROOT_EMAIL=${ROOT_EMAIL}
        - GRAYLOG_PASSWORD_SECRET=${PASSWORD_SECRET}
        - GRAYLOG_ROOT_PASSWORD_SHA2=${ROOT_PASSWORD_SHA2}
        - GRAYLOG_HTTP_PUBLISH_URI=${HTTP_PUBLISH_URI}:9000/
        - GRAYLOG_HTTP_ENABLE_TLS=false
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
      networks:
        - graylog
      restart: always
      depends_on:
        - mongo
        - elasticsearch
      ports:
        - 5044:5044
        - 5044:5044/udp
        # Graylog web interface and REST API
        - 9000:9000
        # Syslog UDP
        - 1514:1514/udp
        # GELF UDP
        - 12201:12201/udp
networks:
    graylog:
      driver: bridge
volumes:
  mongo_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker/mongo_data
  es_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker/es_data
  graylog_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/docker/graylog_data
